---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(plotly)
library(RCurl)
library(jsonlite)
library(dygraphs)
library(htmlwidgets)
library(dplyr)
library(tidyverse) 
library(zoo)
## https://www.cbs.gov.il/en/mediarelease/pages/2020/population-of-israel-on-the-eve-of-2021.aspx
## https://boardsgenerator.cbs.gov.il/Resources/Mifkad/profiles/rep_e_000000.pdf
## data was actualized to 2021  assuming a 2% growth rate and age distribution.



## population distribution from 2008 census
population.byAgeGroup <- list(israel= c("0-19"=	2652110,
                              "20-29"=	1137940,
                              "30-39"=1038500,
                              "40-49"=	814250,
                              "50-59"=745350,
                              "60-69"=	489760,
                              "70-79"=332820,
                              "80-89"=	172820,
                              "90+"=	28650) )
 
## population distribution from 2018 updated to 2021 assuming a population of 9501249  census
population.byAgeGroup <- list(israel= c( "0-19"= 3431120, 	
                                        "20-29"= 1334550,	
                                        "30-39"= 1247094,
                                        "40-49"= 1118330,                                    
                                        "50-59"= 866349,                     
                                        "60-69"= 768743,           	
                                        "70-79"= 458283,                     
                                        "80-89"= 227946,          	
                                          "90+"= 48835 ) )

## population distribution relating the percent vaccinated from
##  https://datadashboard.health.gov.il/COVID-19/general?tileName=vaccinatedByAge and
##   relating from numeric information in https://data.gov.il/api/3/action/datastore_search?resource_id=57410611-936c-49a6-ac3c-838171055b1f&limit=5
population.byAgeGroup <- list(israel= c( "0-19" = 1190401,
                                         "20-29"= 1299566,
                                         "30-39"= 1196741,
                                         "40-49"= 1098347 ,                                
                                         "50-59"= 849489,                
                                         "60-69"= 741823,      	
                                         "70-79"= 490443,                
                                         "80-89"= 225216,     	
                                         "90+"  = 50879    ) )

population.byAgeGroup.percent<- population.byAgeGroup$israel / sum(  population.byAgeGroup$israel ) 

population.byAgeGroup.2019 <- population.byAgeGroup$israel

data_hospitalized = jsonlite::fromJSON(  RCurl::getURL("https://data.gov.il/api/3/action/datastore_search?resource_id=8a51c65b-f95a-4fb8-bd97-65f47109f41f&limit=50000") )
data_vaccinated = jsonlite::fromJSON( RCurl::getURL("https://data.gov.il/api/3/action/datastore_search?resource_id=57410611-936c-49a6-ac3c-838171055b1f&limit=50000") )

data_vaccinated$result$records$VaccinationDate <- as.Date(data_vaccinated$result$records$VaccinationDate)

data_vaccinated$result$records <- data_vaccinated$result$records  %>% arrange( VaccinationDate ) 

data_vaccinated$result$records$Age_group <- as.factor(data_vaccinated$result$records$age_group)
data_vaccinated$result$records$age_group<-NULL
data_vaccinated$result$records$first_dose <- as.integer(data_vaccinated$result$records$first_dose)
data_vaccinated$result$records$second_dose <- as.integer(data_vaccinated$result$records$second_dose)
data_vaccinated$result$records$third_dose <- as.integer(data_vaccinated$result$records$third_dose)

data_vaccinated$result$records[is.na(data_vaccinated$result$records)]<-0


data_vaccinated.final  <- data_vaccinated$result$records %>% group_by(Age_group)  %>% arrange( VaccinationDate, Age_group )  %>% mutate( 
                                                                  first_dose.cumsum=cumsum(first_dose) , 
                                                                  second_dose.cumsum=cumsum(second_dose) ,
                                                                  third_dose.cumsum=cumsum(third_dose) , 
                                                                  not_vaccinated= population.byAgeGroup.2019[as.character(Age_group)]- cumsum(first_dose), 
                                                                  age_group2=population.byAgeGroup.2019[as.character(Age_group)], 
                                                                  .keep="all")



 
data_hospitalized$result$records$event_after_1st_dose[ which(data_hospitalized$result$records$event_after_1st_dose=="<5") ] <- 4
data_hospitalized$result$records$event_after_1st_dose <- as.numeric(data_hospitalized$result$records$event_after_1st_dose)

data_hospitalized$result$records$event_after_2nd_dose[ which(data_hospitalized$result$records$event_after_2nd_dose=="<5") ] <- 4
data_hospitalized$result$records$event_after_2nd_dose <- as.numeric(data_hospitalized$result$records$event_after_2nd_dose)

data_hospitalized$result$records$event_for_not_vaccinated[ which(data_hospitalized$result$records$event_for_not_vaccinated=="<5") ] <- 4
data_hospitalized$result$records$event_for_not_vaccinated <- as.numeric(data_hospitalized$result$records$event_for_not_vaccinated)

data_hospitalized$result$records$Age_group <- as.factor(data_hospitalized$result$records$Age_group)
data_hospitalized$result$records$Week <- as.factor(data_hospitalized$result$records$Week)
data_hospitalized$result$records$Type_of_event <- as.factor(data_hospitalized$result$records$Type_of_event)
data_hospitalized$result$records$Date <- as.Date(do.call("rbind", strsplit(as.character(data_hospitalized$result$records$Week), split=" - ") )[,2])

data_hospitalized$result$records[is.na(data_hospitalized$result$records)]<-0

data_hospitalized.final  <- data_hospitalized$result$records %>% group_by(Age_group)  %>% arrange( Date, Age_group )  %>% mutate( 
  
  CS.patients.1stDose=cumsum(event_after_1st_dose) , 
  CS.patients.2nDose=cumsum(event_after_2nd_dose) ,
  CS.patients.NV=cumsum(event_for_not_vaccinated) , 
 # NormCS.1stDose=cumsum(event_after_1st_dose)/   population.byAgeGroup.2019[as.character(Age_group)] *100 ,
 # NormCS.2nDose=cumsum(event_after_2nd_dose)/ population.byAgeGroup.2019[as.character(Age_group)]*100 ,
#  NormCS.NV=cumsum(event_for_not_vaccinated)/   population.byAgeGroup.2019[as.character(Age_group)]*100 , 
  #### here I relate to the number of peaple vaccinated 10 days before (remember it is a weekly figure)  
  .keep="all")

## here we add a dummy date of ten days to that matching will occur with actually the number of vaccinated 10 days before (to account for time to immunity ) 
data_vaccinated.final$Date <- (data_vaccinated.final$VaccinationDate + 15)
data.final <- merge(as.data.frame(data_hospitalized.final), 
                    as.data.frame(data_vaccinated.final), by=c("Date", "Age_group") )

data.final[["1st_Dose.Norm"]] <-  round(data.final$event_after_1st_dose / data.final$first_dose.cumsum * 100000)
data.final[["2nd_Dose.Norm"]] <-  round(data.final$event_after_2nd_dose / data.final$second_dose.cumsum * 100000)
data.final[["NV.Norm"]] <-  round(data.final$event_for_not_vaccinated / data.final$not_vaccinated * 100000)
 
data.final2 <- data.final  %>% arrange( Date, Age_group, Type_of_event ) %>% 
  select(Date, Age_group, Week, Type_of_event, 
         `1st_dose`=event_after_1st_dose, `2nd_dose`=event_after_2nd_dose, 
         NV=event_for_not_vaccinated, 
         TotN.Vaccinated.1stDose=first_dose.cumsum,
         TotN.Vaccinated.2ndDose=second_dose.cumsum,
         TotN.NotVaccinated=not_vaccinated,
         `1st_Dose.Norm`, `2nd_Dose.Norm`, NV.Norm) 


data.final2.m <- reshape::melt(data.final2, id.vars=c("Age_group", "Week", "Type_of_event", "Date"))



fig <- ggplot(data.final2.m %>% filter(Date > "2021-04-01"), aes(x=Date)) + 
  geom_bar(stat="identity", aes(y=value, group=Age_group, color=Age_group)) +
  facet_wrap( . ~ variable+Type_of_event, ncol=2, scales="free") + 
  theme_bw()



```
 
Image credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Sharingan_triple.svg)

---
class: center, middle

# xaringan
```{r}
fig
```

